"""livro_nome em emprestimos

Revision ID: b3dccf15543b
Revises: fd2900cdb265
Create Date: 2026-10-06 18:45:42.931477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3dccf15543b'
down_revision = 'fd2900cdb265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprestimos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('livro_nome', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprestimos', schema=None) as batch_op:
        batch_op.drop_column('livro_nome')

    # ### end Alembic commands ###
