"""historico.turma vira string, remove FK

Revision ID: d7df9453cb28
Revises: fd2900cdb265
Create Date: 2026-09-24 12:52:20.912156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7df9453cb28'
down_revision = 'fd2900cdb265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('historico_turma_fkey'), type_='foreignkey')
        batch_op.alter_column('turma',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.alter_column('turma',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('historico_turma_fkey'), 'turma', ['turma'], ['turma'])

    # ### end Alembic commands ###
